site_name: Docs as Code
nav:
- Главная страница: index.md
- Guide:
  - Пошаговое руководство по созданию страницы: guide/creatingnewpage.md
  - Справка по Markdown: guide/markdownref.md
theme:
  name: mkdocs
  locale: ru
  include_sidebar: true
  color_mode: true
  user_color_mode_toggle: true
